---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name: "If \[Name of Student\] doesn’t earn an A, then nobody should, because..." Explain your choice and your reasoning.

    -   If Erica Geam doesn’t earn an A, then nobody should, because from day one, she has put in so much effort into her assignments. She wasn’t only applying the material taught in class, but also doing what she could to gain a conceptual understanding of how and why the code works.

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    -   The most difficult part for me was learning how to implement iterations and connect them to simulations because it was tricky to see how each step of the iteration impacted the overall simulation.

3.  What was the easiest part of the class for you? Explain why.

    -   The easiest part for me was using ggplot() to create visualizations like boxplots, histograms, and bar charts. The steps felt straightforward, mistakes were easier to catch, and it allowed me to express my creativity.

4.  What part of the class surprised or interested you the most? Explain why.

    -   The part of the class that interested me the most were the interactive in-class activities, like the puzzle activity at the beginning of the year and using blocks to visualize how joins work. They made the learning process more fun and memorable.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.
